################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@api = https://obuilder.herokuapp.com/api
@local= http://localhost:{{$dotenv PORT}}/api


################################################################################
# Routes
##
################################### pokemon router ############################


### GET one pokemon by id
GET {{local}}/pokemon/179

### GET one pokemon by id
GET {{api}}/pokemon/771




### GET one pokemon by name (not case sensitive nor accent sensitive)
GET {{local}}/pokemon/p

### get all pokemon imunise to a type
GET {{local}}/pokemon/immune/type/5
###get akk resistants pokemons 
GET {{local}}/pokemon/resist/type/8

###GET resistant and imune pokemon from a type
GET  {{local}}/pokemon/resist-immune/type/2
### GET all pokemon
GET {{local}}/pokemon/full-random

###GET pokemon by 2 types
GET {{api}}/pokemon/type/14/17

### GET all pokemon of one type
GET {{local}}/pokemon/gen/5

### GET all pokemon whith one ability
GET {{local}}/pokemon/ability/2

###get all abilities from a pokemon
GET {{local}}/pokemon/292/abilities


### GET all pokemon by generation 
GET {{local}}/pokemon/gen/



################################### team router ############################

### GET a random team of 6 pokemon
GET {{api}}/pokemon/full-random

###POST a team to get a complete team with 6 pokemon
POST {{local}}/pokemon/complet-team
Content-Type: application/json


[
    1
]

###POST a team to get a complete team with 6 pokemon
POST {{local}}/pokemon/complet-team
Content-Type: application/json

[

15

]


################################## type router #############################

### GET all types (with damage relations)
GET {{local}}/type/2


### GET all type with immunity from one type
GET {{local}}/type/immune/5


### GET all types with resistance from one type
GET {{local}}/type/resist/1

### GET all types with resistance or immunity from one type
GET {{local}}/type/resist-imune/2

####POSt get a list of types with resistance or immunity from a list of types
POST {{api}}/type/resist/types
Content-Type: application/json

    [6,5,7,12,15]
    




################################## seeding router #############################

### seed all generations
GET {{local}}/seeding/generations

### seed all types
GET {{local}}/seeding/types

### seed one pokemon
GET {{local}}/seeding/106

### seed all pokemon
GET {{local}}/seeding/all




### seed pokemon abilities
GET {{local}}/seeding/abilities

### seed pokemon abilities 1 
GET {{local}}/seeding/ability/25


### seed /pokemon_has_ability
GET {{local}}/seeding/pokemon_has_ability

####################################cache router #############################

### cache all pokemon
GET {{local}}/cache/all

###########################generation router #################################

### get all generations
GET {{api}}/gen


###get gen_id 
GET {{local}}/seeding/generation_id



################################      USER ROUTER ################################

#### add pokemon in favorite 
POST {{local}}/user/pokemon/1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2MzEyNTc4LCJleHAiOjE2ODYzMTYxNzh9.s7U5LvuIdTy4Qt7FbxcFLc1u7k52fJoXqyAZnpC3eOY

### delete pokemon in favorite 
DELETE {{local}}/user/pokemon/24
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2MzEyNTc4LCJleHAiOjE2ODYzMTYxNzh9.s7U5LvuIdTy4Qt7FbxcFLc1u7k52fJoXqyAZnpC3eOY



### create user

POST {{local}}/user/signup
Content-Type: application/json

{
    "username": "damien10",   
    "password": "P0kemons!",
    "email": "damien10@gmail.com"
}

### create user
POST {{local}}/user/signup
Content-Type: application/json

{
    "username": "damien",   
    "password": "Damien!1",
    "email": "damien100@gmail.com"
}

### login user
POST {{local}}/user/login
Content-Type: application/json

{
    "email" : "damien100@gmail.com",
    "password" : "Damien!1"
}


### login user
POST {{local}}/user/login
Content-Type: application/json

{
    "email" : "damien100@gmail.com",
    "password" : "Damien!1"
}

### logout user
GET {{local}}/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2NTUzODc0LCJleHAiOjE2ODY1NTc0NzR9.V9JMk8DhzDjZulasQywX1fNKBk4_mVFv2hKree5d1cA


### home page
@web = http://localhost:{{$dotenv PORT}}/

GET {{web}}


### create team

POST {{local}}/user/user/team
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2NTU4OTcyLCJleHAiOjE2ODY1NjI1NzJ9.39OfhHs2JwQpvbOsnoyosOwq926AK2ocygDn-yPkgAc

{
    "teamName": "plou4d",
    "pokemonIds": [
        100,
        250,
        30,
        40,
        500,
        100
    ]
}


### get userpage with teams
GET {{local}}/user/userpage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2NTc3OTIyLCJleHAiOjE2ODY1ODE1MjJ9.THZCinVeK7s7mLArMAdbXkPK2wIz8iregT7IcP8ReIw



### add pokemon in favorite

POST {{local}}/user/pokemon/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2NTc3OTIyLCJleHAiOjE2ODY1ODE1MjJ9.THZCinVeK7s7mLArMAdbXkPK2wIz8iregT7IcP8ReIw

### delete team

DELETE {{local}}/user/user/team
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsInVzZXJuYW1lIjoiZGFtaWVuIiwiZW1haWwiOiJkYW1pZW4xMDBAZ21haWwuY29tIiwiaWF0IjoxNjg2NTYwMTg1LCJleHAiOjE2ODY1NjM3ODV9.MQbR-hkhXewF6uN5VPcGIROeOC_8HTbujVzX1_8c9p8

{
 "id":  4

}

########################## abiliy router ##################################"

###get all abilities
GET {{local}}/ability