################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@api = https://boiling-forest-96071.herokuapp.com/api
@local= http://localhost:{{$dotenv PORT}}/api


################################################################################
# Routes
##
################################### pokemon router ############################


### GET one pokemon by id
GET {{api}}/pokemon/14





### GET one pokemon by name (not case sensitive nor accent sensitive)
GET {{api}}/pokemon/pikachu

### get all pokemon imunise
GET {{api}}/pokemon/imune/type/1

###get akk resistants pokemons 
GET {{api}}/pokemon/resist/type/1

###GET resistant and imune pokemon from a type
GET  {{api}}/pokemon/resist/imune/type/2
### GET all pokemon
GET {{api}}/pokemon/full-random

###GET pokemon by 2 types
GET {{api}}/pokemon/type//type/17

### GET all pokemon of one type
GET {{api}}/pokemon/type/3



### GET all pokemon by generation 
GET {{api}}/pokemon/gen/1



################################### team router ############################

### GET a random team of 6 pokemon
GET {{api}}/pokemon/full-random

###POST a team to get a complete team with 6 pokemon
POST {{api}}/pokemon/complet-team
Content-Type: application/json


[
    25
]

###POST a team to get a complete team with 6 pokemon
POST {{local}}/pokemon/complet-team
Content-Type: application/json

[
    10,11,12,13,15
]


################################## type router #############################

### GET all types (with damage relations)
GET {{api}}/type

### GET all type with immunity from one type
GET {{api}}/type/imune/type/1


### GET all types with resistance from one type
GET {{api}}/type/resist/type/1

### GET all types with resistance or immunity from one type
GET {{api}}/type/resist/imune/type/2

####POSt get a list of types with resistance or immunity from a list of types
POST {{api}}/type/resist/types
Content-Type: application/json

    [6,5,7,12,15]
    




################################## seeding router #############################


### seed one pokemon
GET {{api}}/seeding/1

### seed all pokemon
GET {{api}}/seeding/all


### seed all pokemon of one generation   ###TODO
GET {{api}}/seeding/gen/1

### seed all types
GET {{api}}/seeding/types

### seed all generations
GET {{api}}/seeding/generations


####################################cache router #############################

### cache all pokemon
GET {{api}}/cache/all

###########################generation router #################################

### get all generations
GET {{api}}/gen

### create user

POST {{api}}/user/signup
Content-Type: application/json

{
    "username": "rolandlayec",
    "password": "Testtest14*",
    "email": "roland.layec@gmail.com"
}




@web = http://localhost:{{$dotenv PORT}}/

### home page

GET {{web}}