################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@api = https://boiling-forest-96071.herokuapp.com/api
@local= http://localhost:{{$dotenv PORT}}/api


################################################################################
# Routes
##
################################### pokemon router ############################


### GET one pokemon by id
GET {{api}}/pokemon

### GET one pokemon by id
GET {{local}}/pokemon




### GET one pokemon by name (not case sensitive nor accent sensitive)
GET {{local}}/pokemon/pil

### get all pokemon imunise to a type
GET {{local}}/pokemon/immune/type/5
###get akk resistants pokemons 
GET {{local}}/pokemon/resist/type/5

###GET resistant and imune pokemon from a type
GET  {{local}}/pokemon/resist-immune/type/2
### GET all pokemon
GET {{api}}/pokemon/full-random

###GET pokemon by 2 types
GET {{api}}/pokemon/type/14/type/17

### GET all pokemon of one type
GET {{local}}/pokemon/type/30



### GET all pokemon by generation 
GET {{local}}/pokemon/gen/



################################### team router ############################

### GET a random team of 6 pokemon
GET {{api}}/pokemon/full-random

###POST a team to get a complete team with 6 pokemon
POST {{api}}/pokemon/complet-team
Content-Type: application/json


[
    14
]

###POST a team to get a complete team with 6 pokemon
POST {{local}}/pokemon/complet-team
Content-Type: application/json

[

15

]


################################## type router #############################

### GET all types (with damage relations)
GET {{api}}/type

### GET all type with immunity from one type
GET {{api}}/type/immune/type/5


### GET all types with resistance from one type
GET {{api}}/type/resist/type/1

### GET all types with resistance or immunity from one type
GET {{api}}/type/resist/imune/type/2

####POSt get a list of types with resistance or immunity from a list of types
POST {{api}}/type/resist/types
Content-Type: application/json

    [6,5,7,12,15]
    




################################## seeding router #############################


### seed one pokemon
GET {{local}}/seeding/106

### seed all pokemon
GET {{local}}/seeding/all


### seed all types
GET {{local}}/seeding/types

### seed all generations
GET {{local}}/seeding/generations


####################################cache router #############################

### cache all pokemon
GET {{local}}/cache/all

###########################generation router #################################

### get all generations
GET {{api}}/gen

### create user

POST {{api}}/user/signup
Content-Type: application/json

{
    "username": "damien10",   
    "password": "P0kemons!",
    "email": "damien10@gmail.com"
}

### create user
POST {{local}}/user/signup
Content-Type: application/json

{
    "username": "csdfcds",   
    "password": "D2qfqfdsfdsfdsf!",
    "email": "damien2@gmail.com"
}

### login user
POST {{local}}/user/login
Content-Type: application/json

{
    "email" : "damien10@gmail.com",
    "password" : "P0kemons!"
}


### login user
POST {{local}}/user/login
Content-Type: application/json

{
    "email" : "damien105@gmail.com",
    "password" : "P0kemons!", 
    "passwordConfirm" : "P0kemons!"
}


### home page
@web = http://localhost:{{$dotenv PORT}}/

GET {{web}}